

// Required for Dictionary

namespace Mnemosyne.Core.Models.Pipelines
{
    /// <summary>
    /// Represents the output of a successfully completed cognitive pipeline execution.
    /// </summary>
    public class PipelineExecutionResult
    {
        /// <summary>
        /// Gets or sets the primary response message or content generated by the pipeline.
        /// </summary>
        public string ResponseMessage { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets any metadata that was updated or generated during the pipeline execution.
        /// </summary>
        public Dictionary<string, object> UpdatedMetadata { get; set; } = new();
    }
}